export default[

    {
        "Title": "The Hangover",
        "Year": "2009",
        "imdbID": "tt1119646",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNDI2MzBhNzgtOWYyOS00NDM2LWE0OGYtOGQ0M2FjMTI2NTllXkEyXkFqcGc@._V1_SX300.jpg ",
        "Genre": "Comedy",
        "Director": "Todd Phillips",
        "Actors": "Bradley Cooper, Ed Helms, Zach Galifianakis",
        "Plot": "Three friends wake up from a bachelor party in Las Vegas with no memory of the previous night and must piece together what happened.",
        "imdbRating": "7.7",
        "Country": "USA",
        "Runtime": "100 min"
    },
    {
        "Title": "Dumb and Dumber",
        "Year": "1994",
        "imdbID": "tt0109686",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNGQxZDA1MmMtYWQ1Ni00NTJmLTljMjgtZWVmODllODVhMzgyXkEyXkFqcGc@._V1_SX300.jpg ",
        "Genre": "Comedy",
        "Director": "Peter Farrelly, Bobby Farrelly",
        "Actors": "Jim Carrey, Jeff Daniels, Lauren Holly",
        "Plot": "The cross-country adventures of two well-meaning but dim-witted friends who try to return a suitcase full of money to its owner.",
        "imdbRating": "7.3",
        "Country": "USA",
        "Runtime": "107 min"
    },
    {
        "Title": "Anchorman: The Legend of Ron Burgundy",
        "Year": "2004",
        "imdbID": "tt0357413",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTQ2MzYwMzk5Ml5BMl5BanBnXkFtZTcwOTI4NzUyMw@@._V1_SX300.jpg",
        "Genre": "Comedy",
        "Director": "Adam McKay",
        "Actors": "Will Ferrell, Steve Carell, Paul Rudd",
        "Plot": "Ron Burgundy is San Diego's top-rated newsman in the 1970s, but his life changes when a feminist reporter challenges his male-dominated world.",
        "imdbRating": "7.2",
        "Country": "USA",
        "Runtime": "94 min"
    },
    {
        "Title": "The Grand Budapest Hotel",
        "Year": "2014",
        "imdbID": "tt2278388",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg",
        "Genre": "Comedy, Drama",
        "Director": "Wes Anderson",
        "Actors": "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric",
        "Plot": "A hotel concierge and his protégé become embroiled in the theft of a priceless painting and the battle for a family fortune.",
        "imdbRating": "8.1",
        "Country": "USA, Germany",
        "Runtime": "99 min"
    },
    {
        "Title": "Shaun of the Dead",
        "Year": "2004",
        "imdbID": "tt0365748",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzNjZGE4YTUtOWU3OC00Mzg2LThjNWItMzUwYzEwMDgxYmVjXkEyXkFqcGc@._V1_SX300.jpg ",
        "Genre": "Comedy, Horror",
        "Director": "Edgar Wright",
        "Actors": "Simon Pegg, Nick Frost, Kate Ashfield",
        "Plot": "A group of friends tries to survive a zombie apocalypse in a pub in London.",
        "imdbRating": "7.9",
        "Country": "UK",
        "Runtime": "99 min"
    },
    {
        "Title": "Ferris Bueller's Day Off",
        "Year": "1986",
        "imdbID": "tt0091042",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZWYwMjUxNjMtMzE0MC00NDM3LWIxMmQtYmEyNWVjNjdlZGZjXkEyXkFqcGc@._V1_SX300.jpg ",
        "Genre": "Comedy",
        "Director": "John Hughes",
        "Actors": "Matthew Broderick, Alan Ruck, Mia Sara",
        "Plot": "A high school student skips school for the day and goes on a series of adventures in Chicago, all while evading the school's principal.",
        "imdbRating": "7.8",
        "Country": "USA",
        "Runtime": "103 min"
    },
    {
        "Title": "The Hangover Part II",
        "Year": "2011",
        "imdbID": "tt1411250",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTM2MTM4MzY2OV5BMl5BanBnXkFtZTcwNjQ3NzI4NA@@._V1_SX300.jpg",
        "Genre": "Comedy",
        "Director": "Todd Phillips",
        "Actors": "Bradley Cooper, Zach Galifianakis, Ed Helms",
        "Plot": "After the events of the first film, the wolf pack travels to Thailand for Stu's wedding. They have a night they'll never remember, again.",
        "imdbRating": "6.4",
        "Country": "USA",
        "Runtime": "102 min"
    },
    {
        "Title": "21 Jump Street",
        "Year": "2012",
        "imdbID": "tt1232829",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTg2NjJiODctM2IyMS00MmQ5LWI1YmQtNTBjMTI4M2U2YzA5XkEyXkFqcGc@._V1_SX300.jpg ",
        "Genre": "Comedy, Action, Crime",
        "Director": "Phil Lord, Christopher Miller",
        "Actors": "Jonah Hill, Channing Tatum, Ice Cube",
        "Plot": "A pair of underachieving cops are sent back to a local high school to blend in and bring down a synthetic drug ring.",
        "imdbRating": "7.2",
        "Country": "USA",
        "Runtime": "109 min"
    },
    {
        "Title": "Bridesmaids",
        "Year": "2011",
        "imdbID": "tt1478338",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjAyOTMyMzUxNl5BMl5BanBnXkFtZTcwODI4MzE0NA@@._V1_SX300.jpg",
        "Genre": "Comedy, Romance",
        "Director": "Paul Feig",
        "Actors": "Kristen Wiig, Maya Rudolph, Melissa McCarthy",
        "Plot": "A woman’s life unravels as she competes with her best friend for the coveted role of maid of honor at her wedding.",
        "imdbRating": "6.8",
        "Country": "USA",
        "Runtime": "125 min"
    },
    {
        "Title": "Deadpool",
        "Year": "2016",
        "imdbID": "tt1431045",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzY3ZWU5NGQtOTViNC00ZWVmLTliNjAtNzViNzlkZWQ4YzQ4XkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Comedy, Action, Sci-Fi",
        "Director": "Tim Miller",
        "Actors": "Ryan Reynolds, Morena Baccarin, T.J. Miller",
        "Plot": "A former Special Forces operative turned mercenary is subjected to a rogue experiment that leaves him with accelerated healing powers and a quest for revenge.",
        "imdbRating": "8.0",
        "Country": "USA",
        "Runtime": "108 min"
    },
    {
        Title: "Deadpool 2",
        Year: "2018",
        imdbID: "tt5463162",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BNGY3N2ZhYmMtYTlmYi00ZWIzLWJiZWMtMjgxMjljYTk3MDAwXkEyXkFqcGc@._V1_SX300.jpg",
        Genre: "Action, Adventure, Comedy",
        Director: "David Leitch",
        Actors: "Ryan Reynolds, Josh Brolin, Morena Baccarin",
        Plot: "Deadpool forms a team of mutants to protect a young boy with supernatural powers from a time-traveling soldier."
      },
      {
        Title: "Iron Man",
        Year: "2008",
        imdbID: "tt0371746",
        Type: "movie",
        Poster: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg",
        Genre: "Action, Adventure, Sci-Fi",
        Director: "Jon Favreau",
        Actors: "Robert Downey Jr., Gwyneth Paltrow, Jeff Bridges",
        Plot: "After being held captive in an Afghan cave, billionaire industrialist Tony Stark creates a unique weaponized suit of armor to fight evil."
      }
]
