export default[
    {
        "Title": "Longlegs",
        "Year": "2024",
        "imdbID": "tt23468450",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMmJkNGNiNjgtMzFlYy00ZDI5LWI2YzktZGVjYjI5MjQyMGU3XkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror",
        "Director": "Osgood Perkins",
        "Actors": "Nicolas Cage, Maika Monroe",
        "Plot": "An agent uncovers a decades-long secret about a serial killer during his investigation.",
        "imdbRating": "7.2",
        "Country": "USA",
        "Runtime": "104 min"
    },
    {
        "Title": "Tarot",
        "Year": "2024",
        "imdbID": "tt14088510",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNjY3NTkxMjQtZWNjNy00NGU2LTlhOTMtMmRhZGEwNzRmMDcyXkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Mystery",
        "Director": "Marcel Sarmiento",
        "Actors": "Madelaine Petsch, Megan Suri, Karen Gillan",
        "Plot": "A young woman is drawn into a supernatural mystery involving a deadly Tarot card reading.",
        "imdbRating": "7.0",
        "Country": "USA",
        "Runtime": "110 min"
    },
    {
        "Title": "Abigail",
        "Year": "2024",
        "imdbID": "tt27489557",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNmUxMDRiNjQtYjE0NS00OWZkLTlhZjktYjQ1MmNjNDlhNDdkXkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Thriller",
        "Director": "Melissa Barrera",
        "Actors": "Melissa Barrera, Jenna Ortega, Evan Peters",
        "Plot": "A woman struggles with terrifying visions that blur the line between reality and nightmare.",
        "imdbRating": "6.9",
        "Country": "USA",
        "Runtime": "102 min"
    },
    {
        "Title": "Cuckoo",
        "Year": "2024",
        "imdbID": "tt12349832",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTBhMjVkOTQtYWUyOS00ZDVmLWJmMDMtYTg3MTBlMGIzNzkxXkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Thriller",
        "Director": "Tilman Singer",
        "Actors": "Hunter Schafer, Dan Stevens, Jessica Henwick",
        "Plot": "A young woman is drawn into a sinister web of secrets and lies after a mysterious encounter.",
        "imdbRating": "7.1",
        "Country": "Germany, USA",
        "Runtime": "110 min"
    },
    {
        "Title": "Terrifier 3",
        "Year": "2024",
        "imdbID": "tt27911000",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzc2MWUyYzctY2E4Ny00ZTlmLThjNTMtMTViZGI5NjcyN2EzXkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Thriller",
        "Director": "Damien Leone",
        "Actors": "David Howard Thornton, Lauren LaVera, Elliott Fullam",
        "Plot": "A terrifying new chapter in the saga of Art the Clown, as he continues his reign of terror.",
        "imdbRating": "7.5",
        "Country": "USA",
        "Runtime": "105 min"
    },
    {
        "Title": "Beetlejuice Beetlejuice",
        "Year": "2024",
        "imdbID": "tt2049403",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYmRlYzE3ZTYtNjIyZi00MWYyLWEzZDItOWI5NzM1Yjc0NmI5XkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Comedy, Fantasy, Horror",
        "Director": "Tim Burton",
        "Actors": "Michael Keaton, Winona Ryder, Alec Baldwin",
        "Plot": "The mischievous ghost Beetlejuice is unleashed once again to cause chaos in the afterlife and on Earth.",
        "imdbRating": "7.6",
        "Country": "USA",
        "Runtime": "92 min"
    },
    {
        "Title": "Immaculate",
        "Year": "2024",
        "imdbID": "tt23137390",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMWEzYjYyMjQtNTJjYi00ZDQ5LWE4N2MtNWY2ZTgxODNhYWM4XkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Thriller",
        "Director": "Michael Spierig",
        "Actors": "Emma Roberts, Peter Sarsgaard, Kit Harington",
        "Plot": "A young woman discovers a disturbing truth about her family's legacy while undergoing a dangerous and mysterious procedure.",
        "imdbRating": "6.8",
        "Country": "USA",
        "Runtime": "108 min"
    },
    {
        "Title": "Smile",
        "Year": "2022",
        "imdbID": "tt15474916",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNjFhMzBlNzktMjE2Ni00YTMyLWI2YWUtYmM1N2QxMDQwZmZhXkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Thriller",
        "Director": "Parker Finn",
        "Actors": "Sosie Bacon, Kyle Gallner, Caitlin Stasey",
        "Plot": "After witnessing a traumatic event involving a patient, Dr. Rose Cotter begins experiencing disturbing occurrences that threaten her sanity.",
        "imdbRating": "6.7",
        "Country": "USA",
        "Runtime": "115 min"
    },
    {
        "Title": "American Psycho",
        "Year": "2000",
        "imdbID": "tt0144084",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNzBjM2I5ZjUtNmIzNy00OGNkLWIwZDMtOTAwYWUwMzA2YjdlXkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Thriller, Crime",
        "Director": "Mary Harron",
        "Actors": "Christian Bale, Justin Theroux, Josh Lucas",
        "Plot": "A wealthy New York investment banker hides his alternate psychopathic ego from his circle of friends while grappling with his dwindling mental state.",
        "imdbRating": "7.6",
        "Country": "USA",
        "Runtime": "102 min"
    },
    {
        "Title": "Midsommar",
        "Year": "2019",
        "imdbID": "tt8772262",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_SX300.jpg",
        "Genre": "Horror, Drama, Mystery",
        "Director": "Ari Aster",
        "Actors": "Florence Pugh, Jack Reynor, Vilhelm Blomgren",
        "Plot": "A couple travels with friends to Sweden to attend a rural hometown's fabled Swedish mid-summer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.",
        "imdbRating": "7.1",
        "Country": "USA, Sweden",
        "Runtime": "147 min"
    },
    {
        "Title": "Nosferatu: A Symphony of Horror",
        "Year": "1922",
        "imdbID": "tt0013442",
        "Type": "movie",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNDg1OTI1M2MtMTVlMS00ZjFhLTgyMTAtYjIzOWUwZTkyZWE5XkEyXkFqcGc@._V1_SX300.jpg",
        "Genre": "Horror, Drama",
        "Director": "F.W. Murnau",
        "Actors": "Max Schreck, Gustav von Wangenheim, Greta Schröder",
        "Plot": "In this silent classic, a young real estate agent is sent to Transylvania to meet a new client, Count Orlok, who turns out to be a vampire intent on spreading the undead curse to a new land.",
        "imdbRating": "8.0",
        "Country": "Germany",
        "Runtime": "94 min"
    }
]